// meals.js
const meals = [
  {
    keyword: "gaspacho",
    name: "Гаспачо",
    price: 200,
    category: "soups",
    count: "350 г",
    image: "images/gazpacho.jpg",
  },
  {
    keyword: "mushroom_soup",
    name: "Грибной суп-пюре",
    price: 190,
    category: "soups",
    count: "330 г",
    image: "images/mushroom_soup.jpg",
  },
  {
    keyword: "norwegian_soup",
    name: "Норвежский суп",
    price: 275,
    category: "soups",
    count: "350 г",
    image: "images/norwegian_soup.jpg",
  },
  {
    keyword: "borsh",
    name: "Борщ",
    price: 270,
    category: "soups",
    count: "350 г",
    image: "images/borsh.jpg",
  },
  {
    keyword: "chicken_soup",
    name: "Суп-лапша с курицей",
    price: 280,
    category: "soups",
    count: "320 г",
    image: "images/chickensoupe.jpg",
  },

  // Main Dishes
  {
    keyword: "fried potatoes with mushrooms",
    name: "Жареная картошка с грибами",
    price: 150,
    category: "main-dishes",
    count: "400 г",
    image: "images/friedpotatoeswithmushrooms1.jpg",
  },
  {
    keyword: "lasagna",
    name: "Лазанья",
    price: 300,
    category: "main-dishes",
    count: "320 г",
    image: "images/lasagna.jpg",
  },
  {
    keyword: "chicken_cutlets",
    name: "Котлеты из курицы с картофельным",
    price: 350,
    category: "main-dishes",
    count: "350 г",
    image: "images/chickencutletsandmashedpotatoes.jpg",
  },

  // Pizzas
  {
    keyword: "margarita",
    name: "Пицца Маргарита",
    price: 450,
    category: "pizzas",
    count: "400 г",
    image: "images/margarita.jpg",
  },
  {
    keyword: "four cheese",
    name: "Четыре сыра",
    price: 500,
    category: "pizzas",
    count: "400 г",
    image: "images/fourcheese.jpg",
  },

  {
    keyword: "caesar_salad",
    name: "Цезарь",
    price: 250,
    category: "salads",
    count: "250 г",
    image: "images/caesarsalad.jpg",
  },
  {
    keyword: "greek_salad",
    name: "Греческий салат",
    price: 300,
    category: "salads",
    count: "300 г",
    image: "images/greeksalad.jpg",
  },

  // Drinks
  {
    keyword: "orange_juice",
    name: "Апельсиновый сок",
    price: 100,
    category: "drinks",
    count: "300 мл",
    image: "images/orangejuice.jpg",
  },
  {
    keyword: "apple_juice",
    name: "Яблочный сок",
    price: 90,
    category: "drinks",
    count: "300 мл",
    image: "images/applejuice.jpg",
  },
  {
    keyword: "carrot_juice",
    name: "Морковный сок",
    price: 100,
    category: "drinks",
    count: "300 мл",
    image: "images/carrotjuice.jpg",
  },
  {
    keyword: "grapefruit_juice",
    name: "Грейпфрутовый сок",
    price: 110,
    category: "drinks",
    count: "300 мл",
    image: "images/grapefruitjuice.jpg",
  },
];
